import fs from 'node:fs/promises';
import path from 'node:path';
const OUT=path.join(process.cwd(),'public','tracker-db.json');
const TOKENS=['ETH','SOL','BTC','ARB','SEI','PEPE','SUI','LINK','DOGE','OP','FET','AVAX','INJ','TIA','ONDO'];
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function pc(a,b){return n(a)>0&&n(b)>0?((n(b)-n(a))/n(a))*100:0}
function rec(p,t){const now=new Date().toISOString(),pr=n(p.priceUsd),h=n(p.priceChange?.h24),s=pr*(h>=0?.965:.94),buyLow=s*.995,buyHigh=s*1.015,breakout=(pr*(h>=0?1.045:1.03))*1.006,invalidation=s*.965,tp1=pr*1.055,tp2=pr*1.11;return {id:`${p.chainId}-${p.pairAddress}`,pairAddress:p.pairAddress,token:p.baseToken?.symbol||t,pairLabel:`${p.baseToken?.symbol}/${p.quoteToken?.symbol}`,chain:p.chainId,dex:p.dexId,url:p.url,source:'github-actions',signal:'PRIME WATCH',trackedAt:now,lastUpdated:now,signalPrice:pr,currentPrice:pr,maxHigh:pr,maxLow:pr,buyLow,buyHigh,breakout,invalidation,tp1,tp2,rr:Math.abs(tp1-pr)/Math.abs(pr-invalidation),liquidityUsd:n(p.liquidity?.usd),volume24h:n(p.volume?.h24),tx24:n(p.txns?.h24?.buys)+n(p.txns?.h24?.sells),buyPressure:50,hitBuyZone:false,hitBreakout:false,hitTP1:false,hitTP2:false,hitInvalidation:false,bestMovePct:0,worstMovePct:0,currentMovePct:0,status:'ACTIVE',result:'TRACKING',updateCount:1}}
function upd(r,p){const pr=n(p.priceUsd,r.currentPrice),hi=Math.max(n(r.maxHigh,pr),pr),lo=Math.min(n(r.maxLow,pr),pr),bz=r.hitBuyZone||(lo<=r.buyHigh&&hi>=r.buyLow),bo=r.hitBreakout||hi>=r.breakout,t1=r.hitTP1||hi>=r.tp1,t2=r.hitTP2||hi>=r.tp2,inv=r.hitInvalidation||lo<=r.invalidation;let status='ACTIVE',result='TRACKING';if(t2){status='HIT TP2';result='WIN TP2'}else if(t1){status='HIT TP1';result='WIN TP1'}else if(inv){status='INVALIDATED';result='FAILED'}else if(bo){status='HIT BREAKOUT';result='BREAKOUT WATCH'}else if(bz){status='HIT BUY ZONE';result='WAIT BOUNCE'}return {...r,lastUpdated:new Date().toISOString(),currentPrice:pr,maxHigh:hi,maxLow:lo,liquidityUsd:n(p.liquidity?.usd),volume24h:n(p.volume?.h24),tx24:n(p.txns?.h24?.buys)+n(p.txns?.h24?.sells),hitBuyZone:bz,hitBreakout:bo,hitTP1:t1,hitTP2:t2,hitInvalidation:inv,bestMovePct:pc(r.signalPrice,hi),worstMovePct:pc(r.signalPrice,lo),currentMovePct:pc(r.signalPrice,pr),status,result,updateCount:n(r.updateCount)+1}}
async function load(){try{return JSON.parse(await fs.readFile(OUT,'utf8')).records||[]}catch{return[]}}
async function search(q){const res=await fetch(`https://api.dexscreener.com/latest/dex/search?q=${encodeURIComponent(q)}`);const d=await res.json();return d.pairs||[]}
async function main(){const map=new Map((await load()).map(r=>[r.id,r]));for(const t of TOKENS){try{const p=(await search(t)).filter(x=>n(x.liquidity?.usd)>200000&&n(x.volume?.h24)>250000).sort((a,b)=>n(b.volume?.h24)-n(a.volume?.h24))[0];if(p){const id=`${p.chainId}-${p.pairAddress}`;map.set(id,map.has(id)?upd(map.get(id),p):rec(p,t))}await new Promise(r=>setTimeout(r,350))}catch(e){console.warn(t,e.message)}}await fs.mkdir(path.dirname(OUT),{recursive:true});await fs.writeFile(OUT,JSON.stringify({version:'v5-worker',updatedAt:new Date().toISOString(),records:[...map.values()].sort((a,b)=>new Date(b.lastUpdated)-new Date(a.lastUpdated))},null,2));console.log('records',map.size)}
main().catch(e=>{console.error(e);process.exit(1)})
